### ISSUE TITLE
sqlite3.OperationalError, docker on mac

### ISSUE THREAD

**Issue by cam-yates** [kolofordjango/kolo#17] opened 2022-04-13 04:22 UTC
I get one of the following errors when making a request:
```
Traceback (most recent call last):
   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
     self.run()
   File "/usr/local/lib/python3.8/threading.py", line 870, in run
     self._target(*self._args, **self._kwargs)
   File "/usr/local/lib/python3.8/site-packages/kolo/profiler.py", line 254, in save_request_in_db
     save_invocation_in_sqlite(
   File "/usr/local/lib/python3.8/site-packages/kolo/db.py", line 147, in save_invocation_in_sqlite
     cursor.execute(insert_sql, (invocation_id, json_string))
 sqlite3.OperationalError: database is locked
 ```
 ```
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
     self.run()
   File "/usr/local/lib/python3.8/threading.py", line 870, in run
     self._target(*self._args, **self._kwargs)
   File "/usr/local/lib/python3.8/site-packages/kolo/profiler.py", line 254, in save_request_in_db
     save_invocation_in_sqlite(
   File "/usr/local/lib/python3.8/site-packages/kolo/db.py", line 147, in save_invocation_in_sqlite
     cursor.execute(insert_sql, (invocation_id, json_string))
   File "/usr/local/lib/python3.8/contextlib.py", line 120, in __exit__
     next(self.gen)
   File "/usr/local/lib/python3.8/site-packages/kolo/db.py", line 26, in db_cursor
     connection.commit()
 sqlite3.OperationalError: disk I/O error
 ```
This only happens when vsCode is open, if i close the app the error no longer happens and i can later open vsCode to see those recorded requests
 
 Have confirmed that this same project seems fine on a linux machine

**Comment by cam-yates** [comment] 2022-05-22 23:28
@wilhelmklopp Sorry to have only just got back to this.
Ahh yep, that sounds like a suggestion along the right path

swapping the volumes over to `bind` unfortunately hasn't solved the issue, it has slightly changed the issue though.

When using a bind volume there is only the `disk I/O error present`:
```
Exception in thread kolo-save_request_in_db:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/kolo/profiler.py", line 261, in save_request_in_db
    save_invocation_in_sqlite(
  File "/usr/local/lib/python3.8/site-packages/kolo/db.py", line 153, in save_invocation_in_sqlite
    cursor.execute(insert_sql, (invocation_id, json_string))
  File "/usr/local/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/kolo/db.py", line 26, in db_cursor
    connection.commit()
sqlite3.OperationalError: disk I/O error
```

Until a certain point where the error will change to:
```
Exception in thread kolo-save_request_in_db:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/kolo/profiler.py", line 261, in save_request_in_db
    save_invocation_in_sqlite(
  File "/usr/local/lib/python3.8/site-packages/kolo/db.py", line 153, in save_invocation_in_sqlite
    cursor.execute(insert_sql, (invocation_id, json_string))
sqlite3.OperationalError: unable to open database file
```

To test this i've just navigated between the same 2 pages a couple of times for the error to change. There doesn't seem to be a pattern but i'd like to test with a simpler project first and see if that makes it easier to narrow down

**Comment by wilhelmklopp** [comment] 2022-06-15 10:14
@cam-yates sorry to hear that bind mounts didn't solve the problem 😕 

We just released version 1.5.0 of the kolo python package, which defaults to using SQLite's WAL mode. We hope that WAL-mode can resolve this sqlite corruption issue that occurs with docker for mac, but we haven't been able to consistently reproduce the corruption ourselves. 

If you could give version 1.5.0 a try to see if the issue still occurs for you, that would be awesome! Thank you 🙌

**Comment by jurecuhalev** [comment] 2022-10-05 10:00
@wilhelmklopp I'm seeing the same issue on Mac with `kolo==2.0.3`, `Docker version 20.10.17, build 100c701` and `macOS 12.6 (21G115)`.

I tried both volumes binding methods and the error is the same:

```
2022-10-05 09:57:54,965 django.server - "POST /api/v1/endpoint/ HTTP/1.1" 200 74 EXTRA => request: `<socket.socket fd=23, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::ffff:172.19.0.7', 8000, 0, 0), raddr=('::ffff:172.19.0.1', 62108, 0, 0)>` server_time: `05/Oct/2022 09:57:54` status_code: `200`
    return old_run_func(self, *a, **kw)
  File "/usr/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vagrant/.local/lib/python3.9/site-packages/kolo/profiler.py", line 232, in save_request_in_db
    save_invocation_in_sqlite(
  File "/home/vagrant/.local/lib/python3.9/site-packages/kolo/db.py", line 84, in save_invocation_in_sqlite
    with db_cursor(db_path, wal_mode) as cursor:
  File "/usr/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/vagrant/.local/lib/python3.9/site-packages/kolo/db.py", line 20, in db_cursor
Exception in thread kolo-save_request_in_db:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    connection.execute("pragma journal_mode=wal")
sqlite3.OperationalError: unable to open database file
    self.run()
  File "/home/vagrant/.local/lib/python3.9/site-packages/sentry_sdk/integrations/threading.py", line 69, in run
    reraise(*_capture_exception())
  File "/home/vagrant/.local/lib/python3.9/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/home/vagrant/.local/lib/python3.9/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "/usr/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vagrant/.local/lib/python3.9/site-packages/kolo/profiler.py", line 232, in save_request_in_db
    save_invocation_in_sqlite(
  File "/home/vagrant/.local/lib/python3.9/site-packages/kolo/db.py", line 84, in save_invocation_in_sqlite
    with db_cursor(db_path, wal_mode) as cursor:
  File "/usr/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/vagrant/.local/lib/python3.9/site-packages/kolo/db.py", line 20, in db_cursor
    connection.execute("pragma journal_mode=wal")
sqlite3.OperationalError: unable to open database file
```

**Comment by sshishov** [comment] 2022-12-07 12:02
Same for us (latest `kolo` and Mac M1:
```
Exception in thread kolo-save_request_in_db:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/venv/lib/python3.10/site-packages/kolo/profiler.py", line 266, in save_request_in_db
    save_invocation_in_sqlite(self.db_path, self.trace_id, json_data, wal_mode)
  File "/home/user/venv/lib/python3.10/site-packages/kolo/db.py", line 85, in save_invocation_in_sqlite
    with db_cursor(db_path, wal_mode) as cursor:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/user/venv/lib/python3.10/site-packages/kolo/db.py", line 21, in db_cursor
    connection.execute("pragma journal_mode=wal")
sqlite3.OperationalError: unable to open database file
```

**Comment by gautammd** [comment] 2022-12-08 10:56
Any update on this? I have the same error as @sshishov  on Mac M1. It was working until few weeks ago.

**Comment by wilhelmklopp** [comment] 2022-12-08 13:01
Hey everyone! Since I last commented here I've had the opportunity to see this issue up close a bit more, so I've got a better sense now of the things that tend to work to resolve it.

The quickest fix to resolve the issue immediately is to delete the sqlite file which lives at `.kolo/db.sqlite3`. Kolo will automatically create a new sqlite file when it next starts up alongside your Django server. 

If the `sqlite3.OperationalError` comes back straight away after you've deleted the sqlite file, what I've seen work is keeping VSCode closed as kolo recreates the sqlite file. So follow these steps:
- Close VSCode
- `rm .kolo/db.sqlite3`
- start the Django server (kolo will re-create the sqlite file during startup)
- Open VSCode

But overall, this is a quick fix and the error is likely to return at some point. 

A more permanent mitigation that has worked well for some users is enabling "VirtioFS accelerated directory sharing" in the Docker preferences.
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/7718702/206451198-8502665b-03e7-494f-a1da-7fd64c7efe4a.png">

This is new as of Docker 4.6 and is probably a useful change to make even beyond helping avoid this error: https://www.docker.com/blog/speed-boost-achievement-unlocked-on-docker-desktop-4-6-for-mac/


However, the **best permanent solution I've seen is to make use of VSCode's Remote Container's extension**: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers

With this extension, VSCode can open the files in your container directly and any changes you make are directly written inside the container. This avoids the underlying issue that causes the sqlite error entirely. I've not yet had any reports of users still running into issues when using the remote container extension.

Please let me know if any of you are still running into issues after trying any of these steps ☝️ 😄

**Comment by gautammd** [comment] 2022-12-09 08:45
That seemed to have worked for me 🙌 . Thanks @wilhelmklopp .

**Comment by wilhelmklopp** [comment] 2022-12-23 18:05
We've now added some documentation to summarise the recommendations I posted above: https://docs.kolo.app/en/latest/docker.html#docker-on-mac

So I'm going to go ahead and close this issue. If you're still experiencing issues after following the recommendations above, please open another issue 🙏

**Closed by wilhelmklopp** 2022-12-23 18:05 UTC
