### ISSUE TITLE
Not able to open the SQL queries

### ISSUE THREAD

**Issue by JayeshJadhav1008** [kolofordjango/kolo#51] opened 2023-04-21 12:59 UTC
Not able to open the SQL queries

**Comment by wilhelmklopp** [comment] 2023-04-22 07:42
Hi! This is likely a duplicate of #18 so essentially opening that sql query document is really slow, especially if you have lots of queries.

We're aware of this but haven't yet got around to a fix

**Closed** 2023-04-22 07:42 UTC
